# Here override all properties that are specific to DEV profile.
spring:

  profiles: dev

  application:
    name: 'T-Triage Application Demo and Development'

  # Datasource configuration
  datasource:
    platform: h2
    url: 'jdbc:h2:mem:qareport;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=600000'
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: never

    # Liquibase changelog configuration
  liquibase:
    change-log: classpath:db/changelog-master.xml
    drop-first: ${db.drop:false}
    enabled: ${db.liquibase.enable:false}

  h2:
    console:
      enabled: ${db.h2.console.enable:true}
      path: '/h2'
      settings:
        web-allow-others: ${db.h2.console.enable:true}

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

################################################################################################
# Application specific properties
################################################################################################

app:

  # Populate configuration
  populate:
    enable: ${db.populate:true}
    amount: 2
    configuration:
      - ${db.profile:demospecial}
    file: ${db.populate.file:'data_populate_jive.sql'}

  configuration:
    url: ${app.url:http://localhost:8080}
