# Here override all properties that are specific to TEST profile.
spring:

  profiles: test

  application:
    name: 'T-Triage Application Test'


  # Datasource configuration
  datasource:
    url: jdbc:h2:mem:aord_segment_service;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=600000
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    platform: h2

  liquibase:
    change-log: classpath:db/changelog-master.xml
    drop-first: ${db.drop:false}
    enabled: ${db.liquibase.enable:false}
  h2:
    console:
      enabled: false
      path: '/h2'

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect



################################################################################################
# Application specific properties
################################################################################################

app:

  # Populate configuration
  populate:
    enable: ${db.populate:true}
    configuration:
      - ${db.profile:test}

  configuration:
    url: http://localhost:8080
